version: "3.7"

services:

  localstack:
    container_name: localstack
    image: localstack/localstack:0.9.1
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=kinesis
      - KINESIS_ERROR_PROBABILITY=0.0
    volumes:
      - ./docker-setup/localstack/:/docker-entrypoint-initaws.d/
  
  demo-application:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: demo-application